### ISSUE TITLE
Only showing battery on my device

### ISSUE THREAD

**Issue by Thman558** [jnross/Bluetility#12]
When I try to look at other devices battery such as another ios device. It doesn't show anything in the battery or current time.

**Comment by jnross** [comment]
This works fine in my testing.  See this screen recording:

![Screen Recording 2020-10-04 at 8 13 11 AM](https://user-images.githubusercontent.com/798990/95019462-4d41b400-061a-11eb-9617-ee4b166f990e.gif)

If your experience is different, will you you please provide more information?  Include the specific hardware model and software version of both your mac and the target device, and a screen recording similar to the one above.

**Comment by Thman558** [comment]
[untitled folder.zip](https://github.com/jnross/Bluetility/files/5323518/untitled.folder.zip)
The Video Is in here. I had to make it a zip since a 2-minute video wouldn't be able to

**Comment by Thman558** [comment]
The First device is my phone all the others are not mine

**Comment by jnross** [comment]
Looks like you might want to report this bug to Apple :).  Your video pretty clearly shows that Bluetility is behaving as expected and is able to successfully read values like this from other devices.  The most likely explanation is that this one target device is not responding as you expect.  

Have you tried other tools such as [BlueSee](https://apps.apple.com/us/app/bluesee-ble-debugger/id1336679524?mt=12)?  Do you see different results with such tools?

**Comment by jnross** [comment]
I'm going to close this issue since it hasn't moved in several months.  Feel free to re-open it if you have more information!
