### ISSUE TITLE
Does not compile with XCode 9+

### ISSUE THREAD

**Issue by swiftcoder** [jnross/Bluetility#2]
Attempting to compile this project with a newer version of XCode fails, and tells the user to downgrade to XCode 8.

**Comment by jnross** [comment]
True.  There has been little need for active development on this project since Xcode 9 was released, and the latest release still runs fine on macOS 10.14 Mojave.  Is there a particular feature you're interested in working on?

**Comment by swiftcoder** [comment]
No, mostly I just completely failed to notice that there were binary releases available.

**Comment by tobiasoort** [comment]
I submitted a pullrequest (PR #3) that pulls this project into 2019 with full Swift 4.2 support. You can try my branch or wait for jnross to merge the PR.

**Comment by jnross** [comment]
Fixed in recent pushes to master:  4e517c6d89450648c3268da40e57f7c611537145
