### ISSUE TITLE
Will Bluetility support virtual UART service?

### ISSUE THREAD

**Issue by DanielYWoo** [jnross/Bluetility#22]
For example, the most common BLE module BT05 can provide a UART service FFE0 with the feature FFE1. I can use a terminal to send or receive data via that service. Will this be supported?

**Comment by jnross** [comment]
I'm not familiar with this module.  Bluetility does very little that is hardware-specific.  It simply queries for and enumerates all services available on the device, and the characteristics in those services, and allows them to be written to or read from as indicated by properties and permissions on the characteristics.  

So in theory, the answer is yes.  But I have not tested with the device you're referring to.
