### ISSUE TITLE
Mi Band 7 Services not showing, Same problem with iPhone which shows for a brief moment and then the services are blank.

### ISSUE THREAD

**Issue by sg4395** [jnross/Bluetility#26]
Hi there, could you help me with this issue? I have the bluetility program and my ble are shown but the services are just blank. It showed briefly for my iphone but not my bluetooth band that I'm wearing. Any help or advice would be appreciated. Thanks.

**Comment by jnross** [comment]
Hi @sg4395.  I see you closes this issue after opening it.  Did your problem get resolved?
