### ISSUE TITLE
Read not working

### ISSUE THREAD

**Issue by divyeshvora2007** [jnross/Bluetility#28]
Hi ,

I run the code successfully and it will write also but it does not read the value when i am trying to fire the command to my device, ESP32.Some other application from app store it will read and write on my device so there is no issue into the device. I am using MacOS 13.1 and on my iphone 7 i have IOS 15.7.2. Can you help me on these ?

Thanks

**Comment by jnross** [comment]
I have an ESP32 device, and `read` operations work fine for me.  Here is a screen recording which shows me connecting to the device, reading the Manufacturer name characteristic, and then another characteristic that shows a factory version number.  You'll notice that when I click the "Read" button that the timestamp updates even though the value doesn't change.  When you first select a characteristic in the browser, Bluetility reads the value of the characteristic automatically.  If you click the "Read" button, the `read` operation is triggered again.  For reference I'm running macOS 13.2

https://user-images.githubusercontent.com/798990/219877308-7dbac4d2-0930-4e1b-9c78-108540fc8e99.mov

I can't speak to the behavior you're seeing without more information.  Can you provide a screen recording of what you're seeing with Bluetility on your Mac?  And if you're seeing something different with an app on your iPhone, will you provide a screen recording of that as well?  What software is running on your ESP32?

**Comment by jnross** [comment]
Old issue, no response.  Closing.
