### ISSUE TITLE
Right clicked row doesn't show context menu correctly

### ISSUE THREAD

**Issue by gitslav** [jnross/Bluetility#31]
MacOS Ventura 13.4.1
When right clicking in the second column, the first 2 rows can not show the menu at all.
Then the third row show a menu for context of row 1.
The fourth row show a menu for context of row 2.
[![Issue video](https://i.gyazo.com/71a053da3ff8d40e9a9f6815dd1fb67e.gif)](https://gyazo.com/71a053da3ff8d40e9a9f6815dd1fb67e)

**Comment by jnross** [comment]
Fix released in https://github.com/jnross/Bluetility/releases/tag/1.5.1
