### ISSUE TITLE
Crash when attempting to write an invalid hex string.

### ISSUE THREAD

**Issue by jnross** [jnross/Bluetility#5]

**Comment by SecretUnicorn** [comment]
This still occurs for me.
Mac OS Montery

**Comment by jnross** [comment]
@SecretUnicorn: any chance you could share the string you entered that triggered the crash?

**Comment by jnross** [comment]
@SecretUnicorn: I just did a fresh reinstall from Homebrew, and any invalid hex string results in the "shake 'no'" gesture from the text field:

https://user-images.githubusercontent.com/798990/146700812-68a3fdc7-c5fa-459c-8787-dd132fdc7ddc.mov

Your move.
