### ISSUE TITLE
Easy access to device identifiers

### ISSUE THREAD

**Issue by peterkos** [jnross/Bluetility#8]
Unless I'm missing something, it'd be great to be able to right-click and copy the device identifier/serviceUUIDs/local identifier. 

It's helpful when working on embedded devices!

**Comment by jnross** [comment]
Good suggestion.  Such information appears in the tooltip when you hover over a device cell, but it is not yet easily copyable.

**Comment by jnross** [comment]
Hi @peterkos:  Will you try out the new release https://github.com/jnross/Bluetility/releases/tag/1.3 and let me know if this has what you are looking for?  Any other suggestions?
